# Generated by Django 4.0.4 on 2022-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_remove_review_book_remove_review_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
    ]
