# Generated by Django 4.0.4 on 2022-06-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='book_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
